# Generated by Django 6.0.4 on 2026-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('contrasena', models.CharField(max_length=64)),
                ('activo', models.IntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rol_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'usuarios_usuario',
                'managed': False,
            },
        ),
    ]
