# Generated by Django 6.0.4 on 2026-04-30 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ninos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asistio', models.BooleanField(default=True)),
                ('recibio_comida', models.BooleanField(default=False)),
                ('sincronizado', models.BooleanField(default=False)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ninos.nino')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
        ),
    ]
